### ISSUE TITLE
Generate helm chart.

### ISSUE THREAD

**Issue by bwplotka** [brancz/locutus#36]
This is part of https://github.com/observatorium/rndr goals, but @brancz asked me why some of that feature cannot be part of Locutus. Why not, let's discuss 🤗 

For multi-purpose deployment / generation tools like locutus - as a deployment templates maintainer I would love to generate helm charts.

@s-urbaniak asked offline a good question, why we care (: 

For our team use cases we care only about generating resources OR generating simple operator OR build complex operator based on Locutus. 

But for maintaining a viable deployment tool that will fit community use cases... That's a must-have. You don't want to block those open source use cases or .. try to maintain charts alone. See an example of a failed attempt [here](https://github.com/thanos-io/thanos/issues/1820)

CNCF community wants to use charts, no one wants to maintain them, so let's generate those!

**Comment by brancz** [comment]
Locutus is designed with a few interfaces in mind. A render step can have any input, but must always output raw yaml plus a rollout spec. And to run a rollout, whether triggered by running the command or some other trigger must always have raw yaml and a rollout spec as an input. Helm could be an input, but not an output.

In that sense, generating helm is out of scope for this project.

**Comment by bwplotka** [comment]
Make sense, thanks
