### ISSUE TITLE
Parallel rollout

### ISSUE THREAD

**Issue by bwplotka** [brancz/locutus#39]
Is the way to make sure groups within rollout are deployed concurrently? I think this might one of the requirements to move from CMO (cc @s-urbaniak).

If it's not currently implemented (I think it's not 🤔 ) where we could contribute that and what could be potential issues? 👍🏽

**Comment by s-urbaniak** [comment]
yes indeed, that's a great idea :+1:

**Comment by brancz** [comment]
Yes as a matter of facts groups were designed exactly with this in mind.

**Comment by brancz** [comment]
This is done, groups and steps are not parallel by default but they can be optionally configured to be parallel.
