### ISSUE TITLE
Can we add DeepCopyInto method for feedback.StatusCondition

### ISSUE THREAD

**Issue by clyang82** [brancz/locutus#45]
We have switched the crds version from `v1beta1` to `v1` in this PR - https://github.com/observatorium/operator/pull/54.
the `PreserveUnknownFields` cannot be false according to
> By default the apiserver drops unknown fields from the request payload during the decoding step. This marker stops the API server from doing so. It affects fields recursively, but switches back to normal pruning behaviour if nested properties or additionalProperties are specified in the schema. This can either be true or undefined. False is forbidden.
in https://book.kubebuilder.io/reference/markers/crd-processing.html

So we have to clearly define the `Conditions []*feedback.StatusCondition ` https://github.com/observatorium/operator/blob/08f589b69dbd6a0072f7af8f5225c93c905c1fb2/api/v1alpha1/observatorium_types.go#L390
but there is no `DeepCopyInto` for `feedback.StatusCondition`
https://github.com/observatorium/operator/blob/08f589b69dbd6a0072f7af8f5225c93c905c1fb2/api/v1alpha1/zz_generated.deepcopy.go#L349

@brancz @metalmatze any comments or suggestions here? Thanks.

**Comment by brancz** [comment]
I'd be happy to have generated versions of it in this repo. Would that help?

**Comment by clyang82** [comment]
Yes. That helps. Here is the PR - https://github.com/brancz/locutus/pull/46
